# Generated by Django 3.2.8 on 2021-10-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maboto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='supercar', max_length=200),
        ),
    ]
